on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  cmake-configure:
    name: test cmake configure
    runs-on: windows-2022
    env: 
      working-directory: .
    steps:
      - name: Set working directory
        run: |
          echo "Current directory: $(pwd)"  # Debug output
          cmake --preset build-release-msvc
          cmake --build build release-msvc
