on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  cmake-configure:
    name: Test CMake Configure
    runs-on: windows-2022
    steps:
      - name: install vcpkg
      # You may pin to the exact commit or the version.
      # uses: lukka/run-vcpkg@8a5116de2b552d6fc8894e9774aacaf2e5db4823
        uses: lukka/run-vcpkg@v7.6
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Vcpkg
        uses: microsoft/vcpkg-setup@v1

      - name: Set working directory
        run: cd $GITHUB_WORKSPACE
        
      - name: Configure CMake
        run: |
          cmake --preset build-release-msvc

      - name: Build project
        run: |
          cmake --build build release-msvc
