on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  cmake-configure:
    name: Test CMake Configure
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set working directory
        run: cd $GITHUB_WORKSPACE

      - name: Configure CMake
        run: |
          cmake --preset build-release-msvc

      - name: Build project
        run: |
          cmake --build build release-msvc
