name: Main CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/cmake-action.yml'
      - 'cmake/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
  pull_request:
    branches: [ main, feature/* ]
  workflow_dispatch:

env:
  VCPKG_COMMIT_ID: cc288af760054fa489574bd8e22d05aa8fa01e5c

jobs:
  build-and-test-vcpkg:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - debug
          - release
        runtime:
          - all
          - flatrim
          - ae
          - se
          - vr
        compiler:
          - msvc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10.0
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: true

      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/main/CMakeLists.txt
          configurePreset: build-${{ matrix.build-type }}-${{ matrix.compiler }}
          buildPreset: ${{ matrix.build-type }}-${{ matrix.compiler }}
