on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  cmake-configure:
    name: Test CMake Configure
    runs-on: windows-2022
    steps:
      
      - name: run-cmake
        # You may pin to the exact commit or the version.
        # uses: lukka/run-cmake@2ce8982be71b8e9a3c4d5e432135035afd1e76a7
        uses: lukka/run-cmake@v10.7
        with:
          # Path to CMakeLists.txt.
          cmakeListsTxtPath: ${{ $GITHUB_WORKSPACE }}/CMakeLists.txt
          # The name of the workflow preset. Optional, it cannot be used with any other preset input. This value is stored in the WORKFLOW_PRESET_NAME environment variable, and used by the default value of 'workflowPresetCmdString' input.
          # The name of the configure preset. Optional, but at least one of the preset input must be provided. This value is stored in the CONFIGURE_PRESET_NAME environment variable, and used by the default value of 'configurePresetCmdString' input.
          configurePreset: build-release-msvc
          buildPreset: release-msvc
          # Specify which shell to be used when launching commands. 'true' means the default shell is used. 'false' means no shell is used. It also can be an absolute with arguments of the shell to spawn commands with.
          useShell: true
